version: '3'

services:
  aydo-koii-myst-pod:
    container_name: aydo-koii-myst-pod
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 8080:8080
      - 4449:4449

    env_file: .env

    volumes:
      - /app/node_modules
      - /app/dist
      # - ./.mysterium:/root/.mysterium

    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN

    privileged: true
    user: root
    network_mode: host
    restart: unless-stopped
